rpath: Enforce LTLIBRARIES to be automake-canonicalized
As we generate a _la_LDFLAGS name from the lib_LTLIBRARIES name, the
latter needs to be canonicalized, otherwise accessing the generated
LDFLAGS variable results in accessing an unknown variable.

diff --git a/Makefile-rpaths.inc.am b/Makefile-rpaths.inc.am
--- a/Makefile-rpaths.inc.am
+++ b/Makefile-rpaths.inc.am
@@ -3,7 +3,7 @@
 ##
 ## This file is part of the Score-P software ecosystem (http://www.score-p.org)
 ##
-## Copyright (c) 2023,
+## Copyright (c) 2023-2024,
 ## Forschungszentrum Juelich GmbH, Germany
 ##
 ## This software may be modified and distributed under the terms of
@@ -41,9 +41,29 @@
 # gets generated in order to generate $(CONFIG_EXTERNAL_LIBS_HPP), see
 # below.
 #
+#
 # $(RPATHS_MAKEFILE) is generated by config.status and whenever Makefile
-# changes. We create an empty $(RPATHS_MAKEFILE) before recusrively
+# changes. We create an empty $(RPATHS_MAKEFILE) before recursively
 # calling $(MAKE) to prevent an infinite loop.
+
+# ---
+# Ensure that <name> in all lib<name>.la is an automake canonicalized
+# name as <name> is used to create variables. See e.g., the rule
+# `$(CONFIG_EXTERNAL_LIBS_HPP)`. Canonicalized
+# names contain just letters, numbers, the strudel (@), and the
+# underscore.
+
+CLEANFILES += ensure_ltlibraries_canonicalized
+
+ensure_ltlibraries_canonicalized: Makefile
+	@for i in $(lib_LTLIBRARIES:.la=); do \
+	    canononical_name=$$(echo "$$i" | tr -c 'A-Za-z0-9_@\n' '_' ); \
+	    if test "$$canononical_name" != "$$i"; then \
+	        echo "ERROR: $$i.la is not a canonical name. Please change to e.g., $$canononical_name.la." >&2; \
+	        exit 1; \
+	    fi; \
+	done; \
+	touch $@
 
 DISTCLEANFILES += $(RPATHS_MAKEFILE)
 
@@ -52,7 +72,7 @@ $(RPATHS_MAKEFILE): Makefile
 	$(MAKE) $(lib_lt_ldflags)
 
 lib_lt_ldflags = $(lib_LTLIBRARIES:.la=_la_LDFLAGS)
-$(lib_lt_ldflags):
+$(lib_lt_ldflags): ensure_ltlibraries_canonicalized
 	@needs_rpaths_var=$$(echo "$@" | $(SED) "s|_LDFLAGS|_needs_RPATHS|"); \
 	needs_rpaths_value=$$(echo "$($@) $(LDFLAGS)" | $(AWK) ' \
 	    { \
