beautifier: beautify Fortran f90/F90 files
Needs fprettify for beautification, which comes with perftools-dev-10.

diff --git a/common/beautifier/beautify-common b/common/beautifier/beautify-common
--- a/common/beautifier/beautify-common
+++ b/common/beautifier/beautify-common
@@ -1,6 +1,7 @@
 # Common code for beautifier. To be used by pre-commit hook, (make) beautify,
 # and the merge-request's beautification.
-# Needs BEAUTIFY_CONFIG to be set and point to configuration file.
+# Needs BEAUTIFY_CONFIG and BEAUTIFY_F_CONFIG to be set and point to
+# configuration files.
 
 
 # sed and sort might be affected, so be consistent
@@ -8,12 +9,13 @@ export LC_ALL=
 export LANG=C
 
 : ${BEAUTIFY:=uncrustify}
+: ${BEAUTIFY_F:=fprettify}
 
 # Consider (A)dded/(C)opied/(M)odified/(R)enamed files only
 filter=ACMR
 
 # Consider these file extensions only
-extensions="'*.c' '*.h' '*.cc' '*.hh' '*.cpp' '*.hpp' '*.java' '*.c.in' '*.h.in' '*.cc.in' '*.hh.in' '*.cpp.in' '*.hpp.in' '*.java.in'"
+extensions="'*.c' '*.h' '*.cc' '*.hh' '*.cpp' '*.hpp' '*.java' '*.c.in' '*.h.in' '*.cc.in' '*.hh.in' '*.cpp.in' '*.hpp.in' '*.java.in' '*.f90' '*.F90'"
 
 # A path is ignored if the 'hook-beautifier' attribute is 'unset', i.e., the
 # attribute name is prefixed with a dash '-'.
@@ -37,7 +39,14 @@ beautify_candidate()
 
     # Beautify the candidate
     echo "  BEAUTIFY ${1}"
-    $BEAUTIFY -c $BEAUTIFY_CONFIG --no-backup -q "$1"
+    case "${1}" in
+        *.f90|*.F90)
+            $BEAUTIFY_F -c "$BEAUTIFY_F_CONFIG" "$1"
+            ;;
+        *)
+            $BEAUTIFY -c "$BEAUTIFY_CONFIG" --no-backup -q "$1"
+            ;;
+    esac
     if test $? -ne 0
     then
         echo "  ERROR    ${1}"
@@ -45,7 +54,7 @@ beautify_candidate()
     fi
 }
 
-# Check if beautify's config file is available.
+# Check if uncrustify's config file is available.
 if [ "x$BEAUTIFY_CONFIG" = x ]
 then
     echo "  ABORT    variable BEAUTIFY_CONFIG not set."
@@ -53,9 +62,22 @@ then
 fi
 if [ ! -f "$BEAUTIFY_CONFIG" ]
 then
-    echo "  ABORT    Can't find file \"$BEAUTIFY_CONFIG\."
+    echo "  ABORT    Can't find file \"$BEAUTIFY_CONFIG\"."
     exit 1
 fi
+
+# Check if fprettify's config file is available.
+if [ "x$BEAUTIFY_F_CONFIG" = x ]
+then
+    echo "  ABORT    variable BEAUTIFY_F_CONFIG not set."
+    exit 1
+fi
+if [ ! -f "$BEAUTIFY_F_CONFIG" ]
+then
+    echo "  ABORT    Can't find file \"$BEAUTIFY_F_CONFIG\"."
+    exit 1
+fi
+
 # Check for matching beautifier/config version
 exe_version=$($BEAUTIFY --version | tr '[a-z]' '[A-Z]' | sed -e 's/UNCRUSTIFY *//')
 cfg_version=$(head -n 1 $BEAUTIFY_CONFIG | tr '[a-z]' '[A-Z]' | sed -e 's/^# *UNCRUSTIFY *//')
